[pyprland]
plugins = ["scratchpads"]

[scratchpads.terminal]
command = "kitty --class scratchpad"
animation = "fromTop"
class = "kitty-dropterm"

[scratchpads.musikcube]
command = "kitty --class scratchpad -e musikcube"
animation = "fromTop"
class = "kitty-dropterm"
